export const IS_PENDING = 'IS_PENDING';

//POKEMON LIST
export const FETCH_POKEMON_FULFILL = 'FETCH_POKEMON_FULFILL';
export const FETCH_POKEMON_REJECT = 'FETCH_POKEMON_REJECT';

//GET POKEMON
export const GET_POKEMON_FULFILL = 'GET_POKEMON_FULFILL';
export const GET_POKEMON_REJECT = 'GET_POKEMON_REJECT';